### ISSUE TITLE
Crash while interfacing with crate

### ISSUE THREAD

**Issue by Rushmore75** [DonBruce64/MinecraftTransportSimulator#1074]
Tried to open a crate I put in a plane but when the gui went to open the game crashed
[crash-2022-01-26_07.41.29-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/7939776/crash-2022-01-26_07.41.29-client.txt)

```java
java.lang.IllegalStateException: Not building!
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:537)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at com.vicmatskiv.weaponlib.compatibility.CompatibleStaticModelSourceRenderer.func_188616_a(CompatibleStaticModelSourceRenderer.java:107)
	at minecrafttransportsimulator.mcinterface.InterfaceEventsModelLoader.getItemModel(InterfaceEventsModelLoader.java:91)
	at minecrafttransportsimulator.guis.components.GUIComponentItem.render(GUIComponentItem.java:66)
	at minecrafttransportsimulator.guis.components.AGUIBase.render(AGUIBase.java:187)
	at minecrafttransportsimulator.mcinterface.InterfaceEventsEntityRendering.on(InterfaceEventsEntityRendering.java:152)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_35_InterfaceEventsEntityRendering_on_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.renderChat(GuiIngameForge.java:823)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:199)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.client.renderer.BufferBuilder.func_178977_d(BufferBuilder.java:537)
	at net.minecraft.client.renderer.Tessellator.func_78381_a(SourceFile:21)
	at com.vicmatskiv.weaponlib.compatibility.CompatibleStaticModelSourceRenderer.func_188616_a(CompatibleStaticModelSourceRenderer.java:107)
	at minecrafttransportsimulator.mcinterface.InterfaceEventsModelLoader.getItemModel(InterfaceEventsModelLoader.java:91)
	at minecrafttransportsimulator.guis.components.GUIComponentItem.render(GUIComponentItem.java:66)
	at minecrafttransportsimulator.guis.components.AGUIBase.render(AGUIBase.java:187)
	at minecrafttransportsimulator.mcinterface.InterfaceEventsEntityRendering.on(InterfaceEventsEntityRendering.java:152)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_35_InterfaceEventsEntityRendering_on_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.renderChat(GuiIngameForge.java:823)```

**Comment by DonBruce64** [comment]
Odd, does this happen with just IV installed?  If not, can you just remove vicmatskiv.weaponlib?  I suspect that's Vic's Modern Warfare, but can't be sure.  But they are the ones calling the MC rendering to render something when it dang well shouldn't.

**Comment by DonBruce64** [comment]
Found out this is a known VMW issue.  You need to get with them as they have multiple fixes for this.
