### ISSUE TITLE
[1.16.5] Error on server

### ISSUE THREAD

**Issue by Azimkin** [DonBruce64/MinecraftTransportSimulator#1589]
[22:19:05] [Server thread/FATAL]: Error executing task on Server
 java.lang.NullPointerException: null
        at mcinterface1165.PacketEntityCSHandshakeClient.handle(PacketEntityCSHandshakeClient.java:54) ~[mts:?]
        at minecrafttransportsimulator.packets.components.APacketPlayer.handle(APacketPlayer.java:42) ~[mts:?]
        at mcinterface1165.InterfacePacket$WrapperPacket.lambda$handle$0(InterfacePacket.java:137) ~[mts:?]
        at net.minecraftforge.fml.network.NetworkEvent$Context.enqueueWork(NetworkEvent.java:215) ~[forge:?]
        at mcinterface1165.InterfacePacket$WrapperPacket.handle(InterfacePacket.java:126) ~[mts:?]
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.lambda$tryDecode$3(IndexedMessageCodec.java:128) ~[forge:?]
        at java.util.Optional.ifPresent(Optional.java:183) ~[?:?]
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.tryDecode(IndexedMessageCodec.java:128) ~[forge:?]
        at net.minecraftforge.fml.network.simple.IndexedMessageCodec.consume(IndexedMessageCodec.java:162) ~[forge:?]
        at net.minecraftforge.fml.network.simple.SimpleChannel.networkEventListener(SimpleChannel.java:80) ~[forge:?]
        at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[server.jar:?]
        at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[server.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:303) ~[server.jar:?]
        at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[server.jar:?]
        at net.minecraftforge.fml.network.NetworkInstance.dispatch(NetworkInstance.java:86) ~[forge:?]
        at net.minecraftforge.fml.network.NetworkHooks.lambda$onCustomPayload$1(NetworkHooks.java:91) ~[forge:?]
        at java.util.Optional.map(Optional.java:265) ~[?:?]
        at net.minecraftforge.fml.network.NetworkHooks.onCustomPayload(NetworkHooks.java:91) ~[forge:?]
        at net.minecraft.network.play.ServerPlayNetHandler.func_147349_a(ServerPlayNetHandler.java:2580) ~[?:?]
        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:50) ~[?:?]
        at net.minecraft.network.play.client.CCustomPayloadPacket.func_148833_a(CCustomPayloadPacket.java:13) ~[?:?]
        at net.minecraft.network.PacketThreadUtil.func_225383_a(PacketThreadUtil.java:22) ~[?:?]
        at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) ~[?:?]
        at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:886) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:169) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:869) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:863) ~[?:?]
        at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:848) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:781) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:265) ~[?:?]
        at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by DonBruce64** [comment]
Addressed in 22.8.0.
