### ISSUE TITLE
[1.12.2] Server crash - Engine - NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by ProsperCraft** [DonBruce64/MinecraftTransportSimulator#315]
Crash log-
https://gist.github.com/ProsperCraft/8924b6e6228abe3dc02fca293922eb25
`java.lang.NullPointerException: Ticking entity
	at minecrafttransportsimulator.vehicles.parts.APartEngine.updatePart(APartEngine.java:235)
	at minecrafttransportsimulator.vehicles.parts.APartEngineGeared.updatePart(APartEngineGeared.java:19)
	at minecrafttransportsimulator.vehicles.parts.PartEngineCar.updatePart(PartEngineCar.java:18)
	at minecrafttransportsimulator.vehicles.main.EntityVehicleD_Moving.func_70030_z(EntityVehicleD_Moving.java:121)
	at minecrafttransportsimulator.vehicles.main.EntityVehicleE_Powered.func_70030_z(EntityVehicleE_Powered.java:64)
	at minecrafttransportsimulator.vehicles.main.EntityVehicleG_Car.func_70030_z(EntityVehicleG_Car.java:31)`

I am told the vehicle is a  -
Humvee with a V12 Turbit engine

Immersive Vehicles-1.12.2-16.0.0

Modpack - TownCraft 1  https://www.curseforge.com/minecraft/modpacks/towncraft/

**Comment by DonBruce64** [comment]
While this was not fixed in V16.1.0, I did add debug information to the crash report that should tell you exactly what is wrong.  I'm going to close this ticket, but if you can't figure out the issue from that information let me know and we can re-open this.
