### ISSUE TITLE
Problem When Opening "U" Menu In Vehicles 

### ISSUE THREAD

**Issue by jackleofsparta** [DonBruce64/MinecraftTransportSimulator#318]
Not every single time, happens every 5th - 7th time I open the "U" menu in a truck or plane to turn the engines on and the game (sometimes server) crash. Below is a crash log, any suggestions?

Time: 2/21/20 12:42 AM
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at minecrafttransportsimulator.vehicles.parts.APartEngine.updatePart(APartEngine.java:235)
	at minecrafttransportsimulator.vehicles.parts.APartEngineGeared.updatePart(APartEngineGeared.java:19)
	at minecrafttransportsimulator.vehicles.parts.PartEngineCar.updatePart(PartEngineCar.java:18)
	at minecrafttransportsimulator.vehicles.main.EntityVehicleD_Moving.func_70030_z(EntityVehicleD_Moving.java:121)
	at minecrafttransportsimulator.vehicles.main.EntityVehicleE_Powered.func_70030_z(EntityVehicleE_Powered.java:64)
	at minecrafttransportsimulator.vehicles.main.EntityVehicleG_Car.func_70030_z(EntityVehicleG_Car.java:31)
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:389)
	at net.minecraft.world.World.func_72866_a(World.java:1993)
	at net.minecraft.world.World.func_72870_g(World.java:1955)
	at net.minecraft.world.World.func_72939_s(World.java:1759)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1846)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1097)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by jackleofsparta** [comment]
-- Entity being ticked --
Details:
	Entity Type: mts:vehicleg_car (minecrafttransportsimulator.vehicles.main.EntityVehicleG_Car)
	Entity ID: 1530
	Entity Name: entity.vehiclecar.name
	Entity's Exact location: -15553.00, 68.54, 2927.00
	Entity's Block location: World: (-15553,68,2927), Chunk: (at 15,4,15 in -973,182; contains blocks -15568,0,2912 to -15553,255,2927), Region: (-31,5; contains chunks -992,160 to -961,191, blocks -15872,0,2560 to -15361,255,3071)
	Entity's Momentum: -0.00, -0.11, -0.00
	Entity's Passengers: [EntityPlayerSP['JackleOfSparta'/196, l='MpServer', x=-15551.28, y=68.44, z=2928.85]]
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1759)

**Comment by DonBruce64** [comment]
The heck is with all these crashing enigne reports?  I swear it's ALWAYS by the fuel calculations too. You able to post your server and client config files?

**Comment by jackleofsparta** [comment]
Here are the configs for both server and client side.
[mtsconfig(server).LOG](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4238426/mtsconfig.server.LOG)
[mtsconfig(client).LOG](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4238427/mtsconfig.client.LOG)

**Comment by jackleofsparta** [comment]
I just wanted to add, because I'm using buildcraft fuel with the mod it may be on my end. I did also try with adding the buildcraft fuel to the config and the pump worked just fine until I turned the truck on. Also I was practicing flying with the creative engines in the DH3 and nothing went wrong for like two hours of constantly using the U menu.

On a side note I want to thank you for this wonderful mod and really do appreciate what you have done here.

**Comment by DonBruce64** [comment]
Appreciate the love for the mod, even if it's being a PITA!

Can confirm that this is an issue to the client and server configs not being aligned.  In your server config you have these listed as fuels for Diesel engines:
"fuel_gaseous": 0.8,
"fuel_gaseous_heat_1": 0.5,
"fuel_gaseous_heat_2": 0.2

Not having those on the client-side config would cause it to crash.  The pump will let you fuel the vehicle with the fuel as the fueling is done server-side, but once you try to start it and the vehicle on the client attempts to use the fuel that it doesn't know anything about, that's where you get the crash.  Closing this as invalid, but I am aware that there are other fuel-based issues that can cause crashes.  Specifically #315.  If you get that crash please post there.  And if syncing the configs doesn't work, feel free to re-open this ticket.
