### ISSUE TITLE
[Bug] Unexplainable crash after updating IV to version 18.5.0

### ISSUE THREAD

**Issue by StarterCraft** [DonBruce64/MinecraftTransportSimulator#497]
I had tried to update the IV mod and its' packs to the 18.5.0 version for many times. But everytime i get this unexplainable exception while final world assets loading.

`
Exception in server tick loop: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(Unknown Source)
	at java.util.HashMap$ValueIterator.next(Unknown Source)
	at net.minecraft.world.World.func_147448_a(World.java:1949)
	at net.minecraft.world.chunk.Chunk.func_76631_c(Chunk.java:856)
	at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:109)
	at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118)
	at net.minecraft.world.gen.ChunkProviderServer.func_186028_c(ChunkProviderServer.java:89)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:135)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:210)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:233)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)
`

Down there you can get the entire report. **Please help!**
[crash-2020-07-29_21.07.36-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4995035/crash-2020-07-29_21.07.36-server.txt)
**

**Comment by DonBruce64** [comment]
I see no IV code running in that stacktrace.  You must have some core mod that's mis-behaving and messing up core Minecraft code.  The only tips I can give you is that it's some mod that is trying to get chunk data, and it's likely one of these guys:

```
WARNING: coremods are present:
  CamPatchingLoader (CMDCam_v1.4.7_mc1.12.2.jar)
  ItemPatchingLoader (ItemPhysic_Full_1.4.32_mc1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.2.6-1.12.2.jar)
  ServerPropertiesLAN (ServerPropertiesLAN-2.65.jar)
  EmoticonsCore (emoticons-0.2.1-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  BlurPlugin (Blur-1.0.4-14.jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
  CreativePatchingLoader (CreativeCore_v1.10.10_mc1.12.2.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1.jar)
  SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-91.jar)
  TLSkinCapeHookLoader (tlskincape_1.12.2-1.4.jar)
Contact their authors BEFORE contacting forge
```

**Comment by StarterCraft** [comment]
I have no idea what to do though. I thought that there are incompatibilities in latest IV versions with some of my installed mods. Seems like I am forever stuck on v15.10 😭
