### ISSUE TITLE
java.lang.NoClassDefFoundError | Error on startup

### ISSUE THREAD

**Issue by wqsadsddsdf** [DonBruce64/MinecraftTransportSimulator#499]
I get this error on startup every time and i dont know how to fix it.

**Comment by DonBruce64** [comment]
Crash report or it didn't happen.

**Comment by wqsadsddsdf** [comment]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  XaeroMinimapPlugin (Xaeros_Minimap_20.17.0_Forge_1.12.jar)
  Controllable (controllable-0.8.0-mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 8/2/20 10:23 PM
Description: Initializing game

java.lang.NoClassDefFoundError: net/minecraftforge/client/resource/VanillaResourceType
	at minecrafttransportsimulator.wrappers.WrapperRender.registerModels(WrapperRender.java:180)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_15_WrapperRender_registerModels_ModelRegistryEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.client.FMLClientHandler.fireSidedRegistryEvents(FMLClientHandler.java:1055)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireSidedRegistryEvents(FMLCommonHandler.java:758)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:245)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.minecraftforge.client.resource.VanillaResourceType
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 18 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at minecrafttransportsimulator.wrappers.WrapperRender.registerModels(WrapperRender.java:180)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_15_WrapperRender_registerModels_ModelRegistryEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.client.FMLClientHandler.fireSidedRegistryEvents(FMLClientHandler.java:1055)
	at net.minecraftforge.fml.common.FMLCommonHandler.fireSidedRegistryEvents(FMLCommonHandler.java:758)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:629)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:245)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 346706032 bytes (330 MB) / 671088640 bytes (640 MB) up to 5368709120 bytes (5120 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.4.2705 Optifine OptiFine_1.12.2_HD_U_F5 18 mods loaded, 18 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                     | Version      | Source                                                    | Signature                                |
	|:----- |:---------------------- |:------------ |:--------------------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft              | 1.12.2       | minecraft.jar                                             | None                                     |
	| UCH   | mcp                    | 9.42         | minecraft.jar                                             | None                                     |
	| UCH   | FML                    | 8.0.99.99    | forge-1.12.2-14.23.4.2705.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                  | 14.23.4.2705 | forge-1.12.2-14.23.4.2705.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | xaerominimap_core      | 1.12.2-1.0   | minecraft.jar                                             | None                                     |
	| UCH   | controllable           | 0.8.0        | controllable-0.8.0-mc1.12.2.jar                           | None                                     |
	| UCH   | cdm                    | 0.4.1        | cdm-0.4.1-mc1.12.2.jar                                    | None                                     |
	| UCH   | cfm                    | 6.3.0        | cfm-6.3.0-mc1.12.2.jar                                    | None                                     |
	| UCH   | computercraft          | 1.80pr1      | ComputerCraft-Mod-1.12.2.jar                              | None                                     |
	| UCH   | gitwebbuilder          | 1.1          | GitWeb+Builder-1.1.jar                                    | None                                     |
	| UCH   | mts                    | 18.1.0       | Immersive+Vehicles-1.12.2-18.1.0.jar                      | None                                     |
	| UCH   | ivairlinerpack         | 1.0.0        | Golden+Airport+Pack+[Immersive+Vehicles]+0.2.6.jar        | None                                     |
	| UCH   | mtsseagullmilitarypack | 1.4.0        | Immersive+Vehicles+(IV)+Seagull's+military+pack+1.7.4.jar | None                                     |
	| UCH   | iv_tcp                 | 1.0.0        | IV_Trin_Civil_Pack_(extended)_2.5.2.jar                   | None                                     |
	| UCH   | iv_tpp                 | 2.0.0        | IV_Trin_Part_Pack_2.8.1.jar                               | None                                     |
	| UCH   | harvestcraft           | 1.12.2zb     | Pam's+HarvestCraft+1.12.2ze.jar                           | None                                     |
	| UCH   | worldedit              | 6.1.10       | worldedit-forge-mc1.12.2-6.1.10-dist.jar                  | None                                     |
	| UCH   | xaerominimap           | 20.17.0      | Xaeros_Minimap_20.17.0_Forge_1.12.jar                     | None                                     |

	Loaded coremods (and transformers): 
XaeroMinimapPlugin (Xaeros_Minimap_20.17.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
Controllable (controllable-0.8.0-mc1.12.2.jar)
  com.mrcrayfish.controllable.asm.ControllableTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 446.14' Renderer: 'GeForce GTX 1050/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.4.2705
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 1050/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD FX(tm)-8300 Eight-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 12
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 446.14
	OpenGlRenderer: GeForce GTX 1050/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 8

**Comment by DonBruce64** [comment]
Have you tried updating Minecraft Forge to the recommended version?

**Comment by wqsadsddsdf** [comment]
I have it on the latest version for 1.12.2 i think

**Comment by DonBruce64** [comment]
Nope.  Latest is 2854.  You're using 2705.

**Comment by wqsadsddsdf** [comment]
Im so sorry for wasting your time, thank you so much!

**Comment by DonBruce64** [comment]
Did updating Forge work?

**Comment by wqsadsddsdf** [comment]
Yep, works perfectly now
