### ISSUE TITLE
CRASH when placing planes probably me

### ISSUE THREAD

**Issue by minecraftserverr** [DonBruce64/MinecraftTransportSimulator#824]
i was on version 2.01 it happens when you place the Ford Trimotor in any colour

**Comment by minecraftserverr** [comment]
/ Hi. I'm Minecraft, and I'm a crashaholic.

Time: 5/24/21 12:46 PM
Description: Ticking entity

java.lang.IllegalStateException: CauseStackManager called from off main thread (current='Thread{class=class java.lang.Thread, name=Client thread, priority=5, group=java.lang.ThreadGroup[name=main,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}')!
	at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:121)
	at org.spongepowered.common.event.SpongeCauseStackManager.pushCauseFrame(SpongeCauseStackManager.java:240)
	at org.spongepowered.common.event.SpongeCommonEventFactory.callCollideEntityEvent(SpongeCommonEventFactory.java:513)
	at net.minecraft.world.World.func_184144_a(World.java:7076)
	at net.minecraft.client.entity.EntityPlayerSP.func_189810_i(EntityPlayerSP.java:1134)
	at net.minecraft.client.entity.EntityPlayerSP.func_70091_d(EntityPlayerSP.java:1055)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1958)
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1827)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:1011)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at net.minecraft.world.World.redirect$zll000$onCallEntityUpdate(World.java:7295)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:121)
	at org.spongepowered.common.event.SpongeCauseStackManager.pushCauseFrame(SpongeCauseStackManager.java:240)
	at org.spongepowered.common.event.SpongeCommonEventFactory.callCollideEntityEvent(SpongeCommonEventFactory.java:513)
	at net.minecraft.world.World.func_184144_a(World.java:7076)
	at net.minecraft.client.entity.EntityPlayerSP.func_189810_i(EntityPlayerSP.java:1134)
	at net.minecraft.client.entity.EntityPlayerSP.func_70091_d(EntityPlayerSP.java:1055)
	at net.minecraft.entity.EntityLivingBase.func_191986_a(EntityLivingBase.java:1958)
	at net.minecraft.entity.player.EntityPlayer.func_191986_a(EntityPlayer.java:1827)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:2393)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:513)
	at net.minecraft.client.entity.EntityPlayerSP.func_70636_d(EntityPlayerSP.java:1011)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2179)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:234)
	at net.minecraft.client.entity.EntityPlayerSP.func_70071_h_(EntityPlayerSP.java:181)
	at net.minecraft.world.World.redirect$zll000$onCallEntityUpdate(World.java:7295)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

**Comment by minecraftserverr** [comment]
i think im the issue not the mod

**Comment by DonBruce64** [comment]
This is not a IV issue.  This is a Sponge issue.  Note how "spongepowered" is all over that crash report, but nowhere is "minecrafttransportsimulator".
```
java.lang.IllegalStateException: CauseStackManager called from off main thread (current='Thread{class=class java.lang.Thread, name=Client thread, priority=5, group=java.lang.ThreadGroup[name=main,maxpri=10]}', expected='Thread{class=class java.lang.Thread, name=Server thread, priority=5, group=net.minecraftforge.fml.common.thread.SidedThreadGroup[name=SERVER,maxpri=10]}')!
at org.spongepowered.common.event.SpongeCauseStackManager.enforceMainThread(SpongeCauseStackManager.java:121)
```
