### ISSUE TITLE
Server crash with MTS Light Controller Box

### ISSUE THREAD

**Issue by andrboot** [DonBruce64/MinecraftTransportSimulator#891]
Version: 1.12.2-20.0.2
Addon Packs - All of them
Crash Log - 

`java.lang.NullPointerException: Exception ticking world
        at minecrafttransportsimulator.blocks.tileentities.instances.TileEntitySignalController.update(TileEntitySignalController.java:76)
        at minecrafttransportsimulator.mcinterface.BuilderTileEntity$Tickable.func_73660_a(BuilderTileEntity.java:146)
        at com.github.terminatornl.tiquality.tracking.tickexecutors.ForgeTickExecutor.onTileEntityTick(ForgeTickExecutor.java:30)
        at net.minecraft.tileentity.TileEntity.tiquality_doUpdateTick(TileEntity.java:629)
        at com.github.terminatornl.tiquality.tracking.TrackerBase.updateOld(TrackerBase.java:190)
        at com.github.terminatornl.tiquality.tracking.TrackerBase.doRandomBlockTick(TrackerBase.java:314)
        at com.github.terminatornl.tiquality.tracking.TickHub.onRandomBlockTick(TickHub.java:43)
        at net.minecraft.world.WorldServer.redirect$zze000$onRandomBlockTick(WorldServer.java:1941)
        at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
        at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
        at java.lang.Thread.run(Thread.java:748)
`

**Comment by DonBruce64** [comment]
Fixed in V20.0.3.
