### ISSUE TITLE
There is a problem when I open the configure(press the key of configure "p" or other key I customize)

### ISSUE THREAD

**Issue by Telepic** [DonBruce64/MinecraftTransportSimulator#964]
When I press the configure key "p"(or other key I customize), a error brust to occur:
[18:31:06] [main/ERROR] [FML]: FML appears to be missing any signature data. This is not a good thing
[18:33:08] [Client thread/ERROR] [mts]: MTSERROR: Could not obtain any materials for oredict ore name coal
[18:33:40] [JM-VersionCheck-1/ERROR] [journeymap]: Could not check version URL
Oct 08, 2021 6:40:54 PM net.java.games.input.DefaultControllerEnvironment getControllers
WARNING: Found unknown Windows version: Windows 10
Oct 08, 2021 6:40:54 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Attempting to use default windows plug-in.
Oct 08, 2021 6:40:54 PM net.java.games.input.DefaultControllerEnvironment getControllers
INFO: Loading: net.java.games.input.DirectAndRawInputEnvironmentPlugin
[18:40:59] [Client thread/FATAL] [minecraft/Minecraft]: Reported exception thrown!

I think it may be the problem of forge or the missing system files of Windows 10, but I want to know if it is the problem of mod itself. But this mod works normally in the old version without error.
In addition, Your mod is very interesting and very practical for urban servers (it surpasses flan in some aspects). I want to move your mod to a minecraft China community called mcbbs(www.mcbbs.net). May I please do that?(I don't have a curseforge account, so I asked this in GitHub)

**Comment by Telepic** [comment]
It's crashing the mod and I want to try to change the forge version or delete some mods that I installed so that I can ensure whether it's the mods conflict. Not long time to reply you.

The version of the China community is so old and it also called MinecraftTransportSimulator but not ImmersiveTransport🤔, I think the carrier give up the updating.

**Comment by DonBruce64** [comment]
Odd, could you post a crash report?  I won't have much way to fix it without one of them.

Heh, that IS old.  If you wanna re-post it there go right ahead.  I don't mind too much as long as you give credit where it is due.

**Comment by Telepic** [comment]
OK, the crash report is this:
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 10/13/21 1:23 PM
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: 255
	at minecrafttransportsimulator.rendering.instances.RenderText$FontData.getBlockFor(RenderText.java:571)
	at minecrafttransportsimulator.rendering.instances.RenderText$FontData.renderText(RenderText.java:393)
	at minecrafttransportsimulator.rendering.instances.RenderText.draw2DText(RenderText.java:41)
	at minecrafttransportsimulator.guis.components.GUIComponentLabel.renderText(GUIComponentLabel.java:77)
	at minecrafttransportsimulator.mcinterface.BuilderGUI.func_73863_a(BuilderGUI.java:135)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1124)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at minecrafttransportsimulator.rendering.instances.RenderText$FontData.getBlockFor(RenderText.java:571)
	at minecrafttransportsimulator.rendering.instances.RenderText$FontData.renderText(RenderText.java:393)
	at minecrafttransportsimulator.rendering.instances.RenderText.draw2DText(RenderText.java:41)
	at minecrafttransportsimulator.guis.components.GUIComponentLabel.renderText(GUIComponentLabel.java:77)
	at minecrafttransportsimulator.mcinterface.BuilderGUI.func_73863_a(BuilderGUI.java:135)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)

-- Screen render details --
Details:
	Screen name: minecrafttransportsimulator.mcinterface.BuilderGUI
	Mouse location: Scaled: (213, 119). Absolute: (427, 240)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Telepic '/68, l='MpServer', x=140.45, y=66.16, z=-306.79]]
	Chunk stats: MultiplayerChunkCache: 49, 49
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (160,4,-314), Chunk: (at 0,0,6 in 10,-20; contains blocks 160,0,-320 to 175,255,-305), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 1497 game time, 1497 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 13 total; [EntityCreeper['苦力怕'/10, l='MpServer', x=147.50, y=6.00, z=-337.50], EntityCreeper['苦力怕'/11, l='MpServer', x=148.50, y=6.00, z=-336.50], EntityBat['蝙蝠'/12, l='MpServer', x=148.41, y=5.53, z=-333.56], EntityCreeper['苦力怕'/13, l='MpServer', x=147.50, y=6.00, z=-335.50], EntityBat['蝙蝠'/14, l='MpServer', x=147.25, y=7.10, z=-332.27], BuilderEntityRenderForwarder['entity.mts_entity_renderer.name'/302, l='MpServer', x=139.52, y=67.45, z=-306.96], EntityBat['蝙蝠'/15, l='MpServer', x=149.33, y=5.82, z=-335.78], BuilderEntityExisting['entity.mts_entity.name'/303, l='MpServer', x=140.45, y=66.16, z=-306.79], EntityBat['蝙蝠'/16, l='MpServer', x=152.48, y=45.10, z=-277.25], EntityBat['蝙蝠'/17, l='MpServer', x=151.48, y=46.00, z=-277.15], EntityBat['蝙蝠'/18, l='MpServer', x=149.50, y=44.85, z=-276.56], EntityPlayerSP['Telepic '/68, l='MpServer', x=140.45, y=66.16, z=-306.79], EntitySkeleton['骷髏'/221, l='MpServer', x=151.50, y=45.00, z=-278.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_261, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 860775536 bytes (820 MB) / 1157627904 bytes (1104 MB) up to 3221225472 bytes (3072 MB)
	JVM Flags: 11 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx3072m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID         | Version      | Source                               | Signature |
	|:------ |:---------- |:------------ |:------------------------------------ |:--------- |
	| LCHIJA | minecraft  | 1.12.2       | minecraft.jar                        | None      |
	| LCHIJA | mcp        | 9.42         | minecraft.jar                        | None      |
	| LCHIJA | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar        | None      |
	| LCHIJA | forge      | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar        | None      |
	| LCHIJA | mts        | 20.2.0       | Immersive+Vehicles-1.12.2-20.2.0.jar | None      |
	| LCHIJA | btcivilmts | 4.0.0        | BlackThorne Civilian Pack.jar        | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 20.19.15.4835' Renderer: 'Intel(R) HD Graphics 4400'
	Launched Version: HMCL 3.2.139
	LWJGL: 2.9.4
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 20.19.15.4835, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: 繁體中文 (台灣)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz


So I will carry your mod on the Chinese MineCraft community and tagging the curseforge web address and the author is you.
When I release it , I will send the address to you.

**Comment by DonBruce64** [comment]
Can you re-try with this version and if it crashed post the new crash report?  You may have to change it from a .zip to a .jar to get it to work.  Git will not let me post .jar files so I had to change it.

[Immersive Vehicles-1.12.2-20.3.0-BETA12.zip](https://github.com/DonBruce64/MinecraftTransportSimulator/files/7342617/Immersive.Vehicles-1.12.2-20.3.0-BETA12.zip)

**Comment by Telepic** [comment]
It won't crash but there is no content on the bottom and the text is not correct.
The Chinese screenshot
![QQ截图20211014121129](https://user-images.githubusercontent.com/62827387/137251235-4cd9f634-2220-4d42-a3fa-b41e520ef99e.png)
The English Screenshot
![Uploading QQ截图20211014121148.png…]()

**Comment by DonBruce64** [comment]
Fixed in 20.3.0 by removing the obsolete lang files.  It's all English, but it at least works.  We can give it another whirl with Chinese language, but from what other people have told me it's not proper Chinese .
